<%@ Page Title="Детали заявки" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="RedirectRequest.aspx.cs" Inherits="medlab.Documents" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="form-horizontal" style="height: 354px">

<asp:ValidationSummary runat="server" CssClass="text-danger" />
         <asp:GridView ID="GridView1" runat="server"  AutoGenerateColumns="False" ShowFooter="True" ShowHeaderWhenEmpty="True" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="true"   DataKeyNames="reqitem_id" OnRowDeleting="GridView1_RowDeleting">
                <Columns>
                    <asp:BoundField ItemStyle-Width="150px" DataField="item_name" HeaderText="Позиция" Visible="True" />
                    <asp:BoundField ItemStyle-Width="150px" DataField="amount" HeaderText="Количество" Visible="True"/>
                </Columns>
                <SelectedRowStyle BackColor="#66FF33" />
            </asp:GridView>
        <asp:Button ID="Button1" runat="server" Height="34px" OnClick="Button1_Click" Text="Перенаправить" Width="124px" />
        <asp:DropDownList ID="Department" runat="server">
        </asp:DropDownList>
        <asp:ListView ID="ListView1" runat="server" OnItemCommand="RequestListView_OnItemCommand"> 
<LayoutTemplate> 
<ul> 
<asp:PlaceHolder ID="itemPlaceholder" runat="server" /> 
</ul> 

</LayoutTemplate> 
<ItemTemplate> 
<tr style="border: 1px solid #FF9933;"> 
<div id="something" style="border: 1px solid black;"> 

<li> 
<%# Eval("doc_id") %> (<%# Eval("name") %>) 
</li> 
<asp:LinkButton runat="server" 
ID="DownloadItem" 
Text="Скачать" 
CommandName="Download" 
CommandArgument='<%#Eval("doc_id")%>' BorderStyle="Solid" /> 
</div> 
</tr> 
</ItemTemplate> 
<EmptyDataTemplate> 
No data 
</EmptyDataTemplate> 

</asp:ListView>
        <script runat="server"> 
protected void ClientsListView_OnItemCommand(object sender, ListViewCommandEventArgs e) 
{ 
if (String.Equals(e.CommandName, "Download")) 
{ 
SaveFile(Guid.Parse(e.CommandArgument.ToString())); 
} 
} 
</script>

    </div>
</asp:Content>