<%@ Page Title="Перенаправление заявки" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="RedirectRequest.aspx.cs" Inherits="medlab.RedirectRequest" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="form-horizontal" style="height: 354px">

<asp:ValidationSummary runat="server" CssClass="text-danger" />
         <asp:GridView ID="GridView1" runat="server"  AutoGenerateColumns="False" ShowFooter="True" ShowHeaderWhenEmpty="True" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="true"   DataKeyNames="req_id" OnRowDeleting="GridView1_RowDeleting">
                <Columns>
                    <asp:BoundField ItemStyle-Width="150px" DataField="req_id" HeaderText="Запрос" Visible="True" />
                    <asp:BoundField ItemStyle-Width="150px" DataField="dept_name" HeaderText="Департамент" Visible="True"/>
                </Columns>
                <SelectedRowStyle BackColor="#66FF33" />
            </asp:GridView>
        <asp:Button ID="Button1" runat="server" Height="34px" OnClick="Button1_Click" Text="Перенаправить" Width="124px" />
        <asp:DropDownList ID="Department" runat="server">
        </asp:DropDownList>
    </div>
</asp:Content>
