<%@ Page Title="Заявки" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Requests.aspx.cs" Inherits="medlab.Requests" %>
<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
 <h2><%:Title%></h2>   
     <asp:ValidationSummary runat="server" CssClass="text-danger" />
          <asp:ValidationSummary runat="server" CssClass="text-danger" />
         <asp:GridView ID="GridView1" runat="server"  AutoGenerateColumns="False" ShowFooter="True" ShowHeaderWhenEmpty="True" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="true"   DataKeyNames="req_id" OnRowDeleting="GridView1_RowDeleting">
                <Columns>
                    <asp:BoundField ItemStyle-Width="150px" DataField="req_id" HeaderText="Запрос" Visible="True" />
                    <asp:BoundField ItemStyle-Width="150px" DataField="req_date" HeaderText="Дата" Visible="True"/>
                </Columns>
                <SelectedRowStyle BackColor="#66FF33" />
            </asp:GridView>
            <asp:Button ID="Button1" runat="server" Height="34px" OnClick="Button1_Click" Text="Детали" Width="124px" />
    </asp:Content>


