<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CreateItem.aspx.cs" Inherits="medlab.CreateItem" MasterPageFile="~/Site.Master"%>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    
    <div class="form-horizontal">
<asp:ValidationSummary runat="server" CssClass="text-danger" />   
        <div class="form-group">

            
        </div> 
        <asp:UpdatePanel ID="OuterUpdatePanel" runat="server" UpdateMode="Conditional" ChildrenAsTriggers="true">
           
            <ContentTemplate>
                <asp:DropDownList ID="Category" runat="server" CssClass="form-control" OnSelectedIndexChanged="Category_SelectedIndexChanged" AutoPostBack="True">
                </asp:DropDownList>
                <asp:GridView ID="GridView1" runat="server"  AutoGenerateColumns="False" ShowFooter="True" ShowHeaderWhenEmpty="True" AutoGenerateDeleteButton="True"   DataKeyNames="item_id" OnRowDeleting="GridView1_RowDeleting">
                <Columns>
  <asp:BoundField ItemStyle-Width="150px" DataField="item_id" HeaderText="item_id" Visible="False" />
  <asp:BoundField ItemStyle-Width="150px" DataField="item_name" HeaderText="item_name" />
</Columns>
            </asp:GridView>


                   <asp:TextBox ID="NewItemName" runat="server"></asp:TextBox>
    <asp:Button ID="NewItemCreate" runat="server" Text="Создать новый товар" OnClick="NewItemCreate_Click"/>
                </ContentTemplate>


             <Triggers>
                        <asp:AsyncPostBackTrigger ControlID="Category" EventName="SelectedIndexChanged" />
                <asp:AsyncPostBackTrigger ControlID="NewItemCreate" EventName="Click" />
                    </Triggers>
            </asp:UpdatePanel>

            </div>

 
</asp:Content>
