<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CreateItemCategory.aspx.cs" Inherits="medlab.CreateItemCategory" MasterPageFile="~/Site.Master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="form-horizontal">

<asp:ValidationSummary runat="server" CssClass="text-danger" />
        <div class="form-group">
            <asp:GridView ID="GridView1" runat="server"  AutoGenerateColumns="False" ShowFooter="True" ShowHeaderWhenEmpty="True" AutoGenerateDeleteButton="True"   DataKeyNames="cat_id" OnRowDeleting="GridView1_RowDeleting">
                <Columns>
  <asp:BoundField ItemStyle-Width="150px" DataField="cat_id" HeaderText="cat_id" Visible="False" />
  <asp:BoundField ItemStyle-Width="150px" DataField="cat_name" HeaderText="cat_name" />
</Columns>
            </asp:GridView>
            </div>


    </div>
    <asp:TextBox ID="NewCategoryName" runat="server"></asp:TextBox>
    <asp:Button ID="NewCategoryCreate" runat="server" Text="Создать новую категорию товаров" OnClick="NewCategoryCreate_Click"/>

</asp:Content>


