<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CreateDepartment.aspx.cs" Inherits="medlab.CreateDepartment" MasterPageFile="~/Site.Master" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

<div class="form-horizontal">

<asp:ValidationSummary runat="server" CssClass="text-danger" />
        <div class="form-group">
            <asp:GridView ID="GridView1" runat="server"  AutoGenerateColumns="False" ShowFooter="True" ShowHeaderWhenEmpty="True" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting"  DataKeyNames="dept_id">
                <Columns>
  <asp:BoundField ItemStyle-Width="150px" DataField="dept_id" HeaderText="dept_id" Visible="False" />
  <asp:BoundField ItemStyle-Width="150px" DataField="dept_name" HeaderText="dept_name" />
</Columns>
            </asp:GridView>
            </div>


    </div>
    <asp:TextBox ID="NewDeptName" runat="server"></asp:TextBox>
    <asp:Button ID="NewDeptCreate" runat="server" Text="Создать новый отдел" OnClick="NewDeptCreate_Click" />

</asp:Content>

